= Advent Coding Contest 2017
:toc:
:toc-title:
:toclevels: 3
:nofooter:

== Aufgabe 1 - Leben
=== Game of Life
Der ACC 2017 nutzt das Konzept von Conway's Spiel des Lebens <<game-of-life>>, auch Game of Life (GoL) genannt, welches einen eigenen Mikrokosmos aus Zellen simuliert.

Für die Sprachen Java und Python steht in den jeweiligen Ordnern eine Schnittstelle zur Verfügung, welche zur Entwicklung verwendet werden soll.
Die vorgegebenen Methoden sind dabei **unbedingt** zu behalten!

==== Regeln
Um für die nächste Generation eine Veränderung hervorzubringen, muss das Spiel mit einigen Regeln bestückt werden.
Das Muster der Folgegeneration wird dabei für alle Zellen gleichzeitig berechnet, wobei der Zustand einer Zelle in der nächsten Generation vom aktuellen Zustand der Zelle selbst und den aktuellen Zuständen ihrer acht Nachbarzellen abhängt.

Als erste Aufgabe soll eine der Grundregeln implementiert werden

* Eine tote Zelle mit genau drei lebenden Nachbarn wird in der Folgegeneration ins **Leben** gerufen.

==== Muster
Muster aus Zellen werden in folgendem Format angegeben und auch in diesem Format bei der Bewertung erwartet.
[source, ruby]
----
{width}";"{height}";"{generation}";"{width * height * ("0" or "1")) "$")}";"
----
Hier ein Beispiel an Mustern von 6 x 6 Feldern über 3 Generationen.
[source, ruby]
----
6;6;0;000001111001000011$
6;6;1;010001111011010001$
6;6;2;111011111011111011$
6;6;3;111111111111111111$
----

'''

[bibliography]
== Referenzen
* [game-of-life] Wikipedia. Conways Spiel des Lebens. 2017. https://wiki.sh/gol.
