= Advent Coding Contest 2017
:toc:
:toc-title:
:toclevels: 3
:nofooter:

== Aufgabe 2 - Einsamkeit
In der ersten Aufgabe wurde eine Variante von Conway's Spiel des Lebens <<game-of-life>>, auf Basis der bereitgestellten Schnittstelle, mit einer Regel entwickelt.

Die nächste Aufgabe besteht nun darin auch die zweite Grundregel des GoL zu implementieren.

* Eine lebende Zelle mit weniger als zwei lebenden Nachbarn stirbt in der Folgegeneration an **Einsamkeit**.

Zur Berechnung der Folgegeneration werden standardmäßig beide Regeln verwendet.
Regeln können über die vorgegebenen Methoden jederzeit aktiviert und deaktiviert werden.

=== Muster
Muster aus Zellen werden in folgendem Format angegeben und auch in diesem Format bei der Bewertung erwartet.
[source, ruby]
----
{width}";"{height}";"{generation}";"{width * height * ("0" or "1")) "$")}";"
----
Hier ein Beispiel an Mustern von 6 x 6 Feldern über 3 Generationen.
[source, ruby]
----
6;3;0;000001111001000001$
6;3;1;010000010011010000$
6;3;2;000000111000000000$
6;3;3;010000010000010000$
----

'''

[bibliography]
== Referenzen
* [game-of-life] Wikipedia. Conways Spiel des Lebens. 2017. https://wiki.sh/gol.
