= Advent Coding Contest 2017
:toc:
:toc-title:
:toclevels: 3
:nofooter:

== Aufgabe 4 - Reversion
In den ersten drei Aufgaben wurde eine Variante von Conway's Spiel des Lebens <<game-of-life>>, auf Basis der bereitgestellten Schnittstelle, mit ihren drei grundlegenden Regeln entwickelt.

Die nächste Aufgabe besteht nun darin ein Muster zu finden, welches in einer vorangegangenen Generation aufgetreten ist. So wird zum Beispiel das Muster der Generation 3 als Startmuster und das Muster der Generation 0 als Endmuster angegeben.

Zur Berechnung der Folgegeneration werden standardmäßig alle drei Regeln verwendet.
Es soll es jederzeit möglich sein Regeln zu aktivieren oder zu deaktivieren.
Zudem können Regeln auf mehrfach hinzugefügt werden, sodass diese in der Berechnung der Folgegeneration mehrfach berücksichtigt werden.

=== Muster
Muster aus Zellen werden in folgendem Format angegeben und auch in diesem Format bei der Bewertung erwartet.
[source, ruby]
----
{width}";"{height}";"{generation}";"{width * height * ("0" or "1")) "$")}";"
----
Hier ein Beispiel an Mustern von 6 x 6 Feldern über 3 Generationen.
[source, ruby]
----
6;6;3;010000010000010000$
6;6;2;000000111000000000$
6;6;1;010000010001010000$
6;6;0;000001111001000001$
----

'''

[bibliography]
== Referenzen
* [game-of-life] Wikipedia. Conways Spiel des Lebens. 2017. https://wiki.sh/gol.
